<?php
###########################################################################################
#	Megabytes - www.megabytesonline.net
# 	Client: The Bank of Carbondale
#	File: estatements.php - eStatements home page
#			
#
# 	VERSION HISTORY
# 	1.0: EY: 6/14/07 
#
############################################################################################


	$PageTitle = 'eStatements';
	$SloganFile = 'Sestatements.php';
	$PicBar = FALSE;
	

?>
<?php include('includes/header.php'); ?>
<table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td class="leftcolumn">
		<?php include('includes/sidebar.php'); ?>
          <p>&nbsp;</p>
		  <p>&nbsp;</p>
          <p align="center"></p>          </td>
        <td class="rightcolumn">
        
        <?php
			if (!isset($_GET['confirm'])) {
				//No code specified, show form.
		?>
          <div class="header">Activate eStatements</div>
            <p>To activate eStatements, enter your confirmation code from your activation email.</p>
            <form id="form1" name="form1" method="get" action="confirm.php">
              Confirmation Code: 
              <input name="confirm" type="text" id="confirm" maxlength="20" />
                        <input type="submit" name="Submit" id="Submit" value="Activate" />
            </form>            
        <?php 
			} else if ($_GET['confirm'] == '297828722') {
				echo '<h3>Your eStatements have already been activated.</h3>';
				//mail('estatements@tboc.com', 'BOCCE Activation Test', "This is only a test");
		} else { 
		
		if (!is_numeric($_GET['confirm'])) {
			echo '<h3>ERROR: The confirmation code entered is not valid. Please back up and try again.</h3>';
		} else {
		
		//Send email to TBOC
			mail('estatements@tboc.com', 'BOCCE Activation', "
*** BOCCE ***

The confirmation code: {$_GET['confirm']} has been activated.

Go here to complete: http://intranet.int.tboc.com/bocce/login.php?confirm={$_GET['confirm']}

** DO NOT REPLY TO THIS EMAIL **
Generated by tboc.com");


	?>
            <div class="header">Activation Complete</div>
            <p>Thank you! Your eStatements activation is now complete. You should receive your next regular monthly statement by eStatements.</p>
     <?php 
	 }
	 } //end if ?>
          </td>
      </tr>
    </table>
	<?php include('includes/footer.php'); ?>		  