<?php
if (isset($_POST['submit'])) {
	echo "<script type='text/javascript'>alert(\"Post is set.\");</script>";
	$message = "
		*** EMAIL GENERATED BY TBOC.COM SOFTWARE ***
		*** DO NOT REPLY TO THIS EMAIL ***

		Customer Name: {$_POST['CustomerName']}
		Email or Phone: {$_POST['EmailOrPhone']}
		Subject: {$_POST['Subject']}

		Message:
		{$_POST['message']}

		*** DO NOT REPLY TO THIS EMAIL ***
	";
	// mail('newaccounts@tboc.com', 'Email from TBOC.com', $message); // production
	mail('jordan.elder@tboc.com', 'Email from TBOC.com', $message); // testing
	echo 'Your message has been sent. Someone will respond as soon as possible.';
	exit();
}else{
	echo "You must construct a message before submitting this form."
}
?>