<?php
if(!isset($_GET['confirm'])){ // No code specified: show form
	echo "
		<div class='header'>
			<h2>Activate eStatements</h2>
		</div>
		<p>To activate eStatements, enter your confirmation code from your activation email.</p>
		<form id='form1' name='form1' method='get' action='pages/ebanking/estatements_activate.php'>
			Confirmation Code:<input name='confirm' type='text' id='confirm' maxlength='20' />
			<input type='submit' name='Submit' id='Submit' value='Activate' />
		</form>            
	";
}else if($_GET['confirm'] == '297828722'){ // eStatements have already been confirmed
	echo "
		<h3>Your eStatements have already been activated.</h3>
	";
}else{
	if(!is_numeric($_GET['confirm'])){ // if non-numeric characters are entered then it's automatically wrong
		echo "
			<h3>ERROR: The confirmation code entered is not valid. Please back up and try again.</h3>
		";
	}else{ // Send the confirmation email to TBOC
		$message = "
			*** BOCCE ***
			The confirmation code: {$_GET['confirm']} has been activated.
			Go here to complete: http://intranet.int.tboc.com/bocce/login.php?confirm={$_GET['confirm']}
			** DO NOT REPLY TO THIS EMAIL **
			Generated by tboc.com
		";
		mail('estatements@tboc.com', 'BOCCE Activation', $message);
		echo "
			<div class='header'>
				<h2>Activation Complete</h2>
			</div>
			<p>Thank you! Your eStatements activation is now complete. You should receive your next regular monthly statement by eStatements.</p>
		";
	}
}
?>
